// Admin feature lib boundary.
// Keep admin pages/components importing from here so we can
// gradually move feature-specific logic without touching callers.
export {
  addChallenge,
  adminAddEventMember,
  adminRemoveEventMember,
  addEvent,
  deleteChallenge,
  deleteEvent,
  deleteSolver,
  formatRelativeDate,
  getAdminScope,
  getAuditLogs,
  getChallengeDetail,
  getChallengesList,
  getChallengesLite,
  getEventAdmins,
  getEvents,
  getFlag,
  getGlobalAdmins,
  getInfo,
  getSolversAll,
  getSolversByChallengeTitle,
  getSolversByUsername,
  getStatsByRange,
  getUsernameByEmail,
  grantEventAdmin,
  isAdmin,
  isGlobalAdmin,
  listEventJoinRequests,
  listEventMembers,
  regenerateEventJoinKey,
  reviewEventJoinRequest,
  revokeEventAdmin,
  searchUsersByUsername,
  setChallengeActive,
  setChallengeMaintenance,
  setChallengesEvent,
  setEventJoinSettings,
  updateChallenge,
  updateEvent,
} from '@/shared/lib'

export type { AuditLogEntry, EventAdminRow, UserLite } from '@/shared/lib'
