-- ==============================================
-- Dummy Testing Runner (execute in order)
-- ==============================================
-- 1) 01_create_dummy_users.sql
-- 2) 02_create_dummy_teams.sql
-- 3) 03_assign_users_to_team.sql
-- 4) 04_simulate_challenge_solves.sql
-- 5) 05_check_scoreboard.sql
-- 6) 06_smoke_test_all_init_functions.sql
--
-- Notes:
-- - Run after db/init.sql has been applied.
-- - Scripts are designed to be re-runnable (idempotent where practical).
-- - This is testing data/flow only; schema is not modified.
